[logging]
level = "INFO"
format = "[%(asctime)s] [%(levelname)s] %(name)s - %(message)s"

[photo]
default_name = "unknown"

[photo.names]
"55b1bffb3a794523b949da0b1aca60fe"= "tq"
"a63fbd67eb9641778bdb46d5ae35e573" = "oh"

[files]
format = "{name}"
timeformat = "%Y-%m-%d_%H:%M:%S"

[web]
threshold = 80

[scale]
port = "/dev/ttyUSB0"
baudrate = 9600
timeout = 4
# 3 seconds of a pause seems to be slightly overkill
# but it keeps it reliable
# 2.x somewhere is whats neccesary most of the time
pause = 3

precision = 3

[camera]
precision = 1

[camera.colours]
blue = [255, 0, 0]
green = [0, 255, 0]
red = [0, 0, 255]
gray = [127, 127, 127]

[camera.crosshair]
radius = 10
thickness = 1

[process]
data_name = "data"
cameraMatrix = "cameraMatrix.txt"
cameraScaleMatrix = "cameraScaleMatrix.txt"
cameraDistortionMatrix = "cameraDistortionMatrix.txt"

[process.camera]
# Time to wait after turning lights on before capturing
wait = 2

[process.paths]
photos = "photos"
data = "data"
generic = "unknown"

[lights]
pin = 12
level = 1

[measure]
bus = 1
address = 41
range = 2

sample_window = 10

precision = 1

cm_per_unit = 0.1

[readers]
inactivity_timeout = 60
