[photo]
timeformat = "%Y-%m-%d_%H:%M:%S"

[photo.names]
"usb:001,004" = "primary"
"usb:001,005" = "secondary"
"usb:001,006" = "tertiary"
"usb:001,007" = "quaternary"

[web]
threshold = 80

[scale]
port = "/dev/ttyUSB0"
baudrate = 9600
timeout = 4
pause = 3

[camera]

[camera.colours]
blue = [255, 0, 0]
green = [0, 255, 0]
red = [0, 0, 255]
