[photo]

[photo.names]
"55b1bffb3a794523b949da0b1aca60fe"= "tq"
"a63fbd67eb9641778bdb46d5ae35e573" = "oh"

[files]
format = "{time}_{name}"
timeformat = "%Y-%m-%d_%H:%M:%S"

[web]
threshold = 80

[scale]
port = "/dev/ttyUSB0"
baudrate = 9600
timeout = 4
pause = 3

[camera]

[camera.colours]
blue = [255, 0, 0]
green = [0, 255, 0]
red = [0, 0, 255]

[process]
data_name = "data"
cameraMatrix = "cameraMatrix.txt"
cameraScaleMatrix = "cameraScaleMatrix.txt"
cameraDistortionMatrix = "cameraDistortionMatrix.txt"

[process.camera]
# Time to wait after turning lights on before capturing
wait = 2

[process.paths]
photos = "photos"
data = "data"

[lights]
pin = 12
level = 0.0

[measure]
bus = 1
address = 41
range = 3

sample_window = 100